main/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home


urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls'))
]

students/urls.py
from django.urls import path

from .import views


app_name = "students"

urlpatterns = [
    path(
        'charts/<str:type_of>/',
        views.ChartsTemplateView.as_view(),
        name="charts_template"
    ),

    path(
        'charts/subject-marks/data',
        views.SubjectMarksView.as_view(),
        name="subject_marks"
    ),
    path(
        'charts/subject-progress/data',
        views.SubjectProgressChartView.as_view(),
        name="subject_progress"
    ),
]

students/models.py
from django.db import models


class StudentMark(models.Model):

    student_id = models.PositiveIntegerField()
    student_name = models.CharField(max_length=64)
    grade = models.CharField(max_length=32)
    subject = models.CharField(max_length=64)
    year = models.PositiveSmallIntegerField()
    semester = models.PositiveSmallIntegerField()
    mark = models.PositiveSmallIntegerField()

    def __str__(self):
        return f"#{self.student_id} mark"

main/views.py
from django.shortcuts import redirect


def home(request):
    pattern = "students:charts_template"
    type_of = "subject-marks"
    return redirect(pattern, type_of=type_of)

students/views.py
from django.views import View, generic
from django.http import JsonResponse, Http404
from django.db.models import Max, Avg

from .models import StudentMark
from .filters import StudentMarkFilter


class SubjectMarksView(View):

    def get(self, request, *args, **kwargs):
        """ get student marks for each subject """

        main_query = self.get_queryset()
        main_query = self.filter_queryset(main_query)
        avg_queryset = self.get_avg_queryset()
        avg_queryset = self.filter_queryset(avg_queryset)

        subjects, values, avg = self.format_data(main_query, avg_queryset)

        return JsonResponse({
            "subjects": subjects,
            "data": values,
            'avg': avg
        })

    def get_queryset(self):
        queryset = StudentMark.objects.values('subject')
        return queryset.annotate(value=Max('mark'))

    def get_avg_queryset(self):
        queryset = StudentMark.objects.values('subject')
        return queryset.annotate(avg=Avg('mark'))

    def filter_queryset(self, queryset):
        return StudentMarkFilter(
            data=self.request.GET,
            queryset=queryset
        ).qs

    def format_data(self, main_query, avg_queryset):
        chart_data = {}
        subjects = []
        values = []
        avg = []

        # add values
        for d in main_query:
            subject = d["subject"]
            value = d["value"]

            if subject not in chart_data:
                chart_data[subject] = {}

            chart_data[subject]["value"] = value

        # add marks
        for d in avg_queryset:
            subject = d["subject"]
            chart_data[subject]['avg'] = round(d["avg"], 2)

        # format data
        for key, data in chart_data.items():
            subjects.append(key)
            values.append(data["value"])
            avg.append(data["avg"])

        return subjects, values, avg


class SubjectProgressChartView(View):

    def get(self, request, *args, **kwargs):
        """ get student marks for all the years """

        main_query = self.get_queryset()
        main_query = self.filter_queryset(main_query)
        marks, semesters = self.format_data(main_query)

        return JsonResponse({
            "marks": marks,
            "semesters": semesters
        })

    def get_queryset(self):
        queryset = StudentMark.objects.values('year', 'semester', 'subject')
        queryset = queryset.annotate(value=Max('mark'))
        return queryset.order_by("year", 'semester')

    def filter_queryset(self, queryset):
        return StudentMarkFilter(
            data=self.request.GET,
            queryset=queryset
        ).qs

    def format_data(self, queryset):
        subject_marks = {}
        semesters = []

        for d in queryset:
            subject = d["subject"]
            mark = d["value"]
            sem = d["semester"]
            year = d["year"]
            year_with_sem = f"{year}-{sem}"

            if year_with_sem not in semesters:
                semesters.append(year_with_sem)

            if subject not in subject_marks:
                subject_marks[subject] = []

            subject_marks[subject].append(mark)

        return (
            [{"name": k, "data": v} for k, v in subject_marks.items()],
            semesters
        )


class ChartsTemplateView(generic.TemplateView):

    templates = {
        "subject-marks": "students/column_chart.html",
        'subject-progress': "students/progress.html"
    }

    def get_template_names(self):
        type_of = self.kwargs.get("type_of")

        if type_of not in self.templates:
            raise Http404()

        return [self.templates[type_of]]

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter_form"] = StudentMarkFilter().form
        return context

students/templates/students/column_chart.html
{% extends 'base.html' %}


{% block main_content %}

<div class="container">
    {% include 'students/filters.html' %}
    <div class="row">
        <div class="col-sm-12 mt-2">
            <figure class="highcharts-figure">
                <div id="chart"></div>
            </figure>
        </div>
    </div>
</div>

<script>

    var filter_form = $("#filter_form")
    var chart_obj = null;
    var filter_endpoint = "/students/charts/subject-marks/data"

    init_chart()

    function init_chart() {

        $.get(filter_endpoint).done(function (data) {
            chart_obj = Highcharts.chart('chart', {
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'Student marks for each Subject'
                },
                xAxis: {
                    categories: data.subjects,
                    crosshair: true
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Marks (0 - 100)'
                    }
                },
                tooltip: {
                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                        '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
                    footerFormat: '</table>',
                    shared: true,
                    useHTML: true
                },
                plotOptions: {
                    column: {
                        pointPadding: 0.2,
                        borderWidth: 0
                    }
                },
                series: [{
                    name: 'Subjects',
                    data: data.data
                },
                {
                    name: 'Avarage',
                    type: 'spline',
                    data: data.avg,
                }]
            });

        })

    }

    filter_form.find("select").change(function(){
        if (chart_obj == null) return false

        var select_box = $(this)
        var select_value = select_box.val()
        var query_parms = filter_form.serialize()

        var endpoint = filter_endpoint + "?" + query_parms

        $.get(endpoint).done(function(data){
            chart_obj.series[0].setData(data.data)
            chart_obj.series[1].setData(data.avg)
        })
        console.log("select_value", select_value)
    })




</script>

{% endblock main_content %}

students/templates/students/filters.html
{% if filter_form %}

<div class="row">
    <div class="col-sm-12">
        <form id="filter_form">
            <div class="row">
                <div class="col-sm-2"></div>

                {% for field in filter_form %}
                    <div class="col-sm-2">
                        <p class="mb-0 text-center">{{field.label}}</p>
                        {{field}}
                    </div>
                {% endfor %}

                <div class="col-sm-2"></div>
            </div>
        </form>
    </div>
</div>


<script>

$(document).ready(function(){

var filter_form = $("#filter_form")
filter_form.find("select").addClass("form-control")

})
</script>

{% endif %}

students/templates/students/progress.html
{% extends 'base.html' %}


{% block main_content %}

<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <form id="filter_form">
                <div class="row">
                    <div class="col-sm-4"></div>
                    <div class="col-sm-4">
                        <p class="mb-0 text-center">Student id</p>
                        {{filter_form.student_id}}
                    </div>
                    <div class="col-sm-4"></div>
                </div>
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            var filter_form = $("#filter_form")
            filter_form.find("select").addClass("form-control")

        })
    </script>


    <div class="row">
        <div class="col-sm-12 mt-2">
            <figure class="highcharts-figure">
                <div id="chart"></div>
            </figure>
        </div>
    </div>
</div>

<script>
    var filter_form = $("#filter_form")
    var chart_obj = null;
    var filter_endpoint = "/students/charts/subject-progress/data"

    init_chart()

    function init_chart() {
        var first_option = filter_form.find("#id_student_id option:eq(1)")
        var default_sid = first_option.val()
        first_option.attr("selected", "selected")

        var endpoint = filter_endpoint + "?student_id=" + default_sid
        $.get(endpoint).done(function (data) {
            chart_obj = Highcharts.chart('chart', {
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'Student progress over the years'
                },
                xAxis: {
                    categories: data.semesters,
                    crosshair: true
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Marks (0 - 100)'
                    }
                },
                tooltip: {
                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                        '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
                    footerFormat: '</table>',
                    shared: true,
                    useHTML: true
                },
                plotOptions: {
                    column: {
                        pointPadding: 0.2,
                        borderWidth: 0
                    }
                },
                series: data.marks
            });

        })

    }

    filter_form.find("select").change(function () {
        if (chart_obj == null) return false

        var select_box = $(this)
        var select_value = select_box.val()
        var query_parms = filter_form.serialize()

        var endpoint = filter_endpoint + "?" + query_parms

        $.get(endpoint).done(function (data) {
            data.marks.forEach(function (mark, index) {
                chart_obj.series[index].setData(mark.data)
                chart_obj.series[index].update({ name: mark.name }, false);
            })
        })
    })




</script>

{% endblock main_content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Marks Charts</title>
    <link rel="stylesheet" href="{% static 'vendors/bootstrap/bootstrap.min.css' %}" />
    <script src="{% static 'vendors/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/highchart/highchart.min.js' %}"></script>
</head>
<body>
    {% include 'layouts/header.html' %}

    {% block main_content %}{% endblock main_content %}
</body>
</html>

templates/layouts/header.html
<header class="mb-4 p-4">
    <div class="row">
        <div class="col-sm-12 text-center">
            <a class="btn-primary btn-sm text-white m-2"
                href="{% url 'students:charts_template' type_of='subject-marks' %}">
                student marks for each subject
            </a>
            <a class="btn-info btn-sm text-white m-2"
                href="{% url 'students:charts_template' type_of='subject-progress' %}">
                subject progress in all years
            </a>
        </div>
    </div>
</header>